# Generated by Django 2.2.12 on 2020-10-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20201012_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
