# Generated by Django 2.2.12 on 2020-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201012_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
