# Generated by Django 2.2.12 on 2020-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201009_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='closed',
            field=models.BooleanField(blank=True),
        ),
    ]
